"""Add quarter_started column

Revision ID: bfaee3344e2e
Revises: 
Create Date: 2025-06-09 09:24:42.232778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfaee3344e2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('povs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quarter_started', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_povs_quarter_started'), ['quarter_started'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('povs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_povs_quarter_started'))
        batch_op.drop_column('quarter_started')

    # ### end Alembic commands ###
